   import 'package:pfe_test/models/learning_path_model.dart';

final concepts = [
      Concept(
        id: 'var-001',
        name: 'Variables & Data Types',
        description: 'Learn about variables, strings, numbers, and basic data types',
        category: 'Fundamentals',
        difficulty: 1,
        estimatedHours: 2,
        prerequisites: [],
        relatedMissions: ['mission-001', 'mission-002'],
        icon: '📦',
        isCompleted: true,
        completionPercentage: 100,
        startedAt: DateTime.now().subtract(const Duration(days: 30)),
        completedAt: DateTime.now().subtract(const Duration(days: 25)),
      ),
      Concept(
        id: 'cond-001',
        name: 'Conditionals & Logic',
        description: 'Master if/else statements and boolean logic',
        category: 'Control Flow',
        difficulty: 1,
        estimatedHours: 3,
        prerequisites: ['var-001'],
        relatedMissions: ['mission-003', 'mission-004'],
        icon: '🔀',
        isCompleted: true,
        completionPercentage: 100,
        startedAt: DateTime.now().subtract(const Duration(days: 24)),
        completedAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Concept(
        id: 'loop-001',
        name: 'Loops & Iteration',
        description: 'Understand for loops, while loops, and iteration patterns',
        category: 'Control Flow',
        difficulty: 2,
        estimatedHours: 4,
        prerequisites: ['cond-001'],
        relatedMissions: ['mission-005', 'mission-006'],
        icon: '🔁',
        isCompleted: true,
        completionPercentage: 100,
        startedAt: DateTime.now().subtract(const Duration(days: 19)),
        completedAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      Concept(
        id: 'func-001',
        name: 'Functions & Scope',
        description: 'Create reusable functions and understand variable scope',
        category: 'Functions',
        difficulty: 2,
        estimatedHours: 5,
        prerequisites: ['loop-001'],
        relatedMissions: ['mission-007', 'mission-008'],
        icon: '⚙️',
        isCompleted: true,
        completionPercentage: 100,
        startedAt: DateTime.now().subtract(const Duration(days: 14)),
        completedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Concept(
        id: 'list-001',
        name: 'Lists & Collections',
        description: 'Work with lists, tuples, and other collection types',
        category: 'Data Structures',
        difficulty: 2,
        estimatedHours: 4,
        prerequisites: ['func-001'],
        relatedMissions: ['mission-009', 'mission-010'],
        icon: '📋',
        isCompleted: true,
        completionPercentage: 100,
        startedAt: DateTime.now().subtract(const Duration(days: 9)),
        completedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Concept(
        id: 'dict-001',
        name: 'Dictionaries & Maps',
        description: 'Master key-value data structures',
        category: 'Data Structures',
        difficulty: 2,
        estimatedHours: 3,
        prerequisites: ['list-001'],
        relatedMissions: ['mission-011', 'mission-012'],
        icon: '🗺️',
        isCompleted: false,
        completionPercentage: 10,
        startedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Concept(
        id: 'oop-001',
        name: 'Object-Oriented Programming',
        description: 'Learn classes, objects, inheritance, and polymorphism',
        category: 'OOP',
        difficulty: 3,
        estimatedHours: 8,
        prerequisites: ['dict-001', 'func-001'],
        relatedMissions: ['mission-013', 'mission-014'],
        icon: '🏗️',
        isCompleted: false,
        completionPercentage: 0,
      ),
      Concept(
        id: 'err-001',
        name: 'Error Handling',
        description: 'Handle exceptions and write robust error-handling code',
        category: 'Advanced',
        difficulty: 3,
        estimatedHours: 3,
        prerequisites: ['oop-001'],
        relatedMissions: ['mission-015', 'mission-016'],
        icon: '⚠️',
        isCompleted: false,
        completionPercentage: 0,
      ),
      Concept(
        id: 'file-001',
        name: 'File I/O & Modules',
        description: 'Read/write files and organize code with modules',
        category: 'Advanced',
        difficulty: 3,
        estimatedHours: 4,
        prerequisites: ['err-001'],
        relatedMissions: ['mission-017', 'mission-018'],
        icon: '📁',
        isCompleted: false,
        completionPercentage: 0,
      ),
    ];

    final milestones = [
      LearningPathMilestone(
        id: 'milestone-001',
        title: 'Python Basics',
        description: 'Master the fundamentals of Python programming',
        conceptIds: ['var-001', 'cond-001', 'loop-001'],
        order: 1,
        isUnlocked: true,
        isCompleted: true,
        completionPercentage: 100,
        icon: '🎯',
        completedAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      LearningPathMilestone(
        id: 'milestone-002',
        title: 'Functions & Data Structures',
        description: 'Learn to write functions and work with collections',
        conceptIds: ['func-001', 'list-001', 'dict-001'],
        order: 2,
        isUnlocked: true,
        isCompleted: false,
        completionPercentage: 70,
        icon: '🔧',
        unlockedAt: DateTime.now().subtract(const Duration(days: 14)),
      ),
      LearningPathMilestone(
        id: 'milestone-003',
        title: 'Object-Oriented Programming',
        description: 'Master OOP concepts and design patterns',
        conceptIds: ['oop-001', 'err-001'],
        order: 3,
        isUnlocked: false,
        isCompleted: false,
        completionPercentage: 0,
        icon: '🏛️',
      ),
      LearningPathMilestone(
        id: 'milestone-004',
        title: 'Advanced Topics',
        description: 'Explore file handling, modules, and more',
        conceptIds: ['file-001'],
        order: 4,
        isUnlocked: false,
        isCompleted: false,
        completionPercentage: 0,
        icon: '🚀',
      ),
    ];


class LearningPathSampleData {
  static LearningPath getSamplePythonPath() {
 

    return LearningPath(
      userId: 'user-123',
      topic: 'Python',
      milestones: milestones,
      concepts: concepts,
      totalConceptsCompleted: 5,
      totalConcepts: 9,
      overallProgressPercentage: 56,
      startedAt: DateTime.now().subtract(const Duration(days: 30)),
      currentLevel: 'Intermediate', missions: [],
    );
  }
}
